<?php

namespace Database\Seeders;

use App\Models\Job;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class JobsTableSeeder extends Seeder
{
    public function run(): void
    {
        $jobs = [
            [
                'id' => 1,
                'user_id' => 1,
                'company_name' => 'x c c bm nyurjhtyh',
                'company_logo_url' => null,
                'company_location' => 'trhyneyn',
                'job_title' => 'gneyjsdtg',
                'job_type' => 'Full-Time',
                'salary_range' => '123456',
                'description' => 'qsdfercgtg',
                'tags' => null,
                'application_link' => null,
                'status' => 'under_review',
                'applicants_count' => 0,
                'posted_at' => Carbon::parse('2026-03-17 16:03:04'),
                'created_at' => Carbon::parse('2026-03-17 16:03:04'),
                'updated_at' => Carbon::parse('2026-03-17 16:03:04'),
            ],
            [
                'id' => 2,
                'user_id' => 1,
                'company_name' => 'MyTeacher Institute',
                'company_logo_url' => null,
                'company_location' => 'Port Harcourt',
                'job_title' => 'LARAVEL DEVELOPER',
                'job_type' => 'Part-Time',
                'salary_range' => '₦400,000',
                'description' => 'Must have strong knowledge of LARAVEL FRAMEWORK and how to integrate API\'S an AI into projects.',
                'tags' => ['Laravel', 'PHP', 'API', 'AI'],
                'application_link' => 'https://example.com/apply',
                'status' => 'active',
                'applicants_count' => 0,
                'posted_at' => Carbon::parse('2026-03-19 07:56:42'),
                'created_at' => Carbon::parse('2026-03-19 07:56:42'),
                'updated_at' => Carbon::parse('2026-03-19 07:56:42'),
            ],
            [
                'id' => 3,
                'user_id' => 1,
                'company_name' => 'MICHAEL',
                'company_logo_url' => null,
                'company_location' => 'Lagos',
                'job_title' => 'Web designer',
                'job_type' => 'Full-Time',
                'salary_range' => '500,000',
                'description' => 'Should have a good knowledge of PHP, JAVASCRIPT, CSS, and Tailwind CSS',
                'tags' => ['PHP', 'JavaScript', 'CSS', 'Tailwind'],
                'application_link' => 'https://example.com/apply',
                'status' => 'active',
                'applicants_count' => 0,
                'posted_at' => Carbon::parse('2026-03-19 13:54:20'),
                'created_at' => Carbon::parse('2026-03-19 13:54:20'),
                'updated_at' => Carbon::parse('2026-03-19 13:54:20'),
            ],
            [
                'id' => 4,
                'user_id' => 1,
                'company_name' => 'Henry Sweet',
                'company_logo_url' => null,
                'company_location' => 'Abuja',
                'job_title' => 'Digital Marketer',
                'job_type' => 'Part-Time',
                'salary_range' => '300,000',
                'description' => 'Digital marketing specialist needed',
                'tags' => ['SEO', 'Social Media', 'Content Marketing'],
                'application_link' => 'https://example.com/apply',
                'status' => 'active',
                'applicants_count' => 0,
                'posted_at' => Carbon::parse('2026-03-19 14:03:47'),
                'created_at' => Carbon::parse('2026-03-19 14:03:47'),
                'updated_at' => Carbon::parse('2026-03-19 14:03:47'),
            ],
            [
                'id' => 5,
                'user_id' => 1,
                'company_name' => 'Myteacher',
                'company_logo_url' => null,
                'company_location' => 'Port Harcourt',
                'job_title' => 'Developer',
                'job_type' => 'Full-Time',
                'salary_range' => '350,000',
                'description' => 'Full stack developer needed',
                'tags' => ['React', 'Node.js', 'MongoDB'],
                'application_link' => 'https://example.com/apply',
                'status' => 'active',
                'applicants_count' => 0,
                'posted_at' => Carbon::parse('2026-03-19 16:08:26'),
                'created_at' => Carbon::parse('2026-03-19 16:08:26'),
                'updated_at' => Carbon::parse('2026-03-19 16:08:26'),
            ],
            [
                'id' => 6,
                'user_id' => 1,
                'company_name' => 'TechCorp Solutions',
                'company_logo_url' => null,
                'company_location' => 'Remote',
                'job_title' => 'Senior FrontEnd Developer',
                'job_type' => 'Remote',
                'salary_range' => '$80,000 - $120,000',
                'description' => 'Looking for an experienced frontend developer',
                'tags' => ['React', 'TypeScript', 'Tailwind'],
                'application_link' => 'https://example.com/apply',
                'status' => 'active',
                'applicants_count' => 0,
                'posted_at' => Carbon::parse('2026-03-23 14:07:02'),
                'created_at' => Carbon::parse('2026-03-23 14:07:02'),
                'updated_at' => Carbon::parse('2026-03-23 14:07:02'),
            ],
            [
                'id' => 7,
                'user_id' => 1,
                'company_name' => 'Frustrated',
                'company_logo_url' => null,
                'company_location' => 'Remote',
                'job_title' => 'Frustrated Developer',
                'job_type' => 'Contract',
                'salary_range' => '$60,000',
                'description' => 'We need a frustrated developer who can handle pressure',
                'tags' => ['JavaScript', 'React', 'Stress Management'],
                'application_link' => 'https://example.com/apply',
                'status' => 'active',
                'applicants_count' => 0,
                'posted_at' => Carbon::parse('2026-03-23 14:51:32'),
                'created_at' => Carbon::parse('2026-03-23 14:51:32'),
                'updated_at' => Carbon::parse('2026-03-23 14:51:32'),
            ],
            [
                'id' => 8,
                'user_id' => 1,
                'company_name' => 'qwertyuiop',
                'company_logo_url' => null,
                'company_location' => 'Test Location',
                'job_title' => 'zxcvbnm,.',
                'job_type' => 'Full-Time',
                'salary_range' => '123456',
                'description' => 'Test job description',
                'tags' => null,
                'application_link' => 'https://example.com/apply',
                'status' => 'active',
                'applicants_count' => 0,
                'posted_at' => Carbon::parse('2026-03-23 15:19:32'),
                'created_at' => Carbon::parse('2026-03-23 15:19:32'),
                'updated_at' => Carbon::parse('2026-03-23 15:19:32'),
            ],
            [
                'id' => 9,
                'user_id' => 1,
                'company_name' => 'OnTheGoSystems',
                'company_logo_url' => 'https://weworkremotely.com/assets/IsotypeV2-46827a1758e8369ac198b0dde837eeaa4227718aa08599df20c37c23da12327c.svg',
                'company_location' => 'Remote',
                'job_title' => 'Full-Stack PHP developer',
                'job_type' => 'Remote',
                'salary_range' => 'USD 290 / week',
                'description' => 'Looking for a skilled PHP developer',
                'tags' => ['PHP', 'JavaScript', 'WordPress'],
                'application_link' => 'https://weworkremotely.com/job-seekers/account/register',
                'status' => 'active',
                'applicants_count' => 0,
                'posted_at' => Carbon::parse('2026-03-23 16:53:31'),
                'created_at' => Carbon::parse('2026-03-23 16:53:31'),
                'updated_at' => Carbon::parse('2026-03-23 16:53:31'),
            ],
            [
                'id' => 13,
                'user_id' => 1,
                'company_name' => 'Test Company With Tags',
                'company_logo_url' => 'https://via.placeholder.com/48',
                'company_location' => 'Lagos, Nigeria',
                'job_title' => 'Full Stack Developer',
                'job_type' => 'Full-Time',
                'salary_range' => '$80,000 / year',
                'description' => 'A great job opportunity',
                'tags' => ['React', 'Laravel', 'Tailwind CSS', 'JavaScript'],
                'application_link' => 'https://example.com/apply',
                'status' => 'active',
                'applicants_count' => 0,
                'posted_at' => Carbon::parse('2026-03-25 13:18:58'),
                'created_at' => Carbon::parse('2026-03-25 13:18:58'),
                'updated_at' => Carbon::parse('2026-03-25 13:18:58'),
            ],
            [
                'id' => 14,
                'user_id' => 1,
                'company_name' => 'OnTheGoSystems',
                'company_logo_url' => 'https://weworkremotely.com/assets/IsotypeV2-46827a1758e8369ac198b0dde837eeaa4227718aa08599df20c37c23da12327c.svg',
                'company_location' => 'Remote',
                'job_title' => 'Full-Stack PHP developer',
                'job_type' => 'Contract',
                'salary_range' => 'USD 290 / week',
                'description' => 'Contract PHP developer needed',
                'tags' => ['PHP', 'Laravel', 'MySQL'],
                'application_link' => 'https://weworkremotely.com/job-seekers/account/register',
                'status' => 'active',
                'applicants_count' => 0,
                'posted_at' => Carbon::parse('2026-03-25 14:07:06'),
                'created_at' => Carbon::parse('2026-03-25 14:07:06'),
                'updated_at' => Carbon::parse('2026-03-25 14:07:06'),
            ],
            [
                'id' => 15,
                'user_id' => 1,
                'company_name' => 'OnTheGoSystems',
                'company_logo_url' => 'https://weworkremotely.com/assets/IsotypeV2-46827a1758e8369ac198b0dde837eeaa4227718aa08599df20c37c23da12327c.svg',
                'company_location' => 'Remote',
                'job_title' => 'Full-Stack PHP developer',
                'job_type' => 'Remote',
                'salary_range' => 'USD 290 / week',
                'description' => 'Another PHP developer position',
                'tags' => ['PHP', 'WordPress', 'React'],
                'application_link' => 'https://weworkremotely.com/job-seekers/account/register',
                'status' => 'active',
                'applicants_count' => 0,
                'posted_at' => Carbon::parse('2026-03-25 14:37:58'),
                'created_at' => Carbon::parse('2026-03-25 14:37:58'),
                'updated_at' => Carbon::parse('2026-03-25 14:37:58'),
            ],
        ];

        foreach ($jobs as $job) {
            Job::updateOrCreate(
                ['id' => $job['id']],
                $job
            );
        }
        
        $this->command->info('Jobs seeded successfully! Total: ' . count($jobs));
    }
}